services:
  # Frontend - React + Vite (Static Site)
  # Nota: Backend foi integrado ao frontend para funcionar offline
  - type: web
    name: edusolo-frontend
    runtime: static
    buildCommand: "cd frontend && npm ci && npm run build"
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20.11.0

