services:
  # Backend API - FastAPI
  - type: web
    name: edusolo-api
    runtime: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: "*"  # Configure com o domínio do frontend em produção
    healthCheckPath: /

  # Frontend - React + Vite (Static Site)
  - type: web
    name: edusolo-frontend
    runtime: static
    buildCommand: "cd frontend && npm ci && npm run build"
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: VITE_API_URL
        fromService:
          type: web
          name: edusolo-api
          property: url

