services:
  # Backend API - FastAPI
  - type: web
    name: edusolo-api
    runtime: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: "*"  # Configure com o domínio do frontend em produção
    healthCheckPath: /

  # Frontend - React + Vite
  - type: web
    name: edusolo-frontend
    runtime: node
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: VITE_API_URL
        fromService:
          type: web
          name: edusolo-api
          property: url

